services:
  db:
    image: postgres:16
    container_name: rf_postgres
    environment:
      POSTGRES_USER: rf
      POSTGRES_PASSWORD: rf123
      POSTGRES_DB: rfdb
    ports:
      - "5433:5432"
    volumes:
      - rfdb_data:/var/lib/postgresql/data

volumes:
  rfdb_data:
